/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    3DList: typeof import('./src/components/modules/3DList/index.vue')['default']
    ApplicationIcon: typeof import('./src/components/icons/ApplicationIcon.vue')['default']
    CalendarIcon: typeof import('./src/components/icons/CalendarIcon.vue')['default']
    ClassSourcesIcon: typeof import('./src/components/icons/ClassSourcesIcon.vue')['default']
    CompanyManagementIcon: typeof import('./src/components/icons/CompanyManagementIcon.vue')['default']
    DownArrowIcon: typeof import('./src/components/icons/DownArrowIcon.vue')['default']
    DownloadIcon: typeof import('./src/components/icons/DownloadIcon.vue')['default']
    ElCarousel: typeof import('element-plus/es')['ElCarousel']
    ElCarouselItem: typeof import('element-plus/es')['ElCarouselItem']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    FireIcon: typeof import('./src/components/icons/FireIcon.vue')['default']
    FolderWithColorIcon: typeof import('./src/components/icons/FolderWithColorIcon.vue')['default']
    InfoListItem: typeof import('./src/components/modules/InfoListItem/index.vue')['default']
    JournalIcon: typeof import('./src/components/icons/JournalIcon.vue')['default']
    LeftArrowIcon: typeof import('./src/components/icons/LeftArrowIcon.vue')['default']
    LeftnavV1: typeof import('./src/components/modules/leftnavV1/index.vue')['default']
    MagnifyGlass: typeof import('./src/components/icons/MagnifyGlass.vue')['default']
    MenuIcon: typeof import('./src/components/icons/MenuIcon.vue')['default']
    MessageIcon: typeof import('./src/components/icons/MessageIcon.vue')['default']
    MoonIcon: typeof import('./src/components/icons/MoonIcon.vue')['default']
    MoreIcon: typeof import('./src/components/icons/MoreIcon.vue')['default']
    NavBar: typeof import('./src/components/modules/NavBar/index.vue')['default']
    Notebook: typeof import('./src/components/modules/notebook/index.vue')['default']
    NotificationIcon: typeof import('./src/components/icons/NotificationIcon.vue')['default']
    NudgeIcon: typeof import('./src/components/icons/NudgeIcon.vue')['default']
    PhoneIcon: typeof import('./src/components/icons/PhoneIcon.vue')['default']
    PopList: typeof import('./src/components/modules/PopList/index.vue')['default']
    ProductionIcon: typeof import('./src/components/icons/ProductionIcon.vue')['default']
    ProjectManagementIcon: typeof import('./src/components/icons/ProjectManagementIcon.vue')['default']
    ResourceInfoCard: typeof import('./src/components/modules/InfoCard/ResourceInfoCard/index.vue')['default']
    RightArrowIcon: typeof import('./src/components/icons/RightArrowIcon.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SettingIcon: typeof import('./src/components/icons/SettingIcon.vue')['default']
    ShoppingIcon: typeof import('./src/components/icons/ShoppingIcon.vue')['default']
    ShowInfoCard: typeof import('./src/components/modules/InfoCard/ShowInfoCard/index.vue')['default']
    ShowInfoCardTaskWithGroup: typeof import('./src/components/modules/InfoCard/ShowInfoCardTaskWithGroup/index.vue')['default']
    ShowInfoCardWithChart: typeof import('./src/components/modules/InfoCard/ShowInfoCardWithChart/index.vue')['default']
    ShowInfoCardWithList: typeof import('./src/components/modules/InfoCard/ShowInfoCardWithList/index.vue')['default']
    SignButton: typeof import('./src/components/modules/SignButton/index.vue')['default']
    StretchNav: typeof import('./src/components/modules/stretchNav/index.vue')['default']
    StretchPersonalCard: typeof import('./src/components/modules/StretchPersonalCard/index.vue')['default']
    SunIcon: typeof import('./src/components/icons/SunIcon.vue')['default']
    TaskWithGroup: typeof import('./src/components/modules/TaskWithGroup/index.vue')['default']
    UpArrowIcon: typeof import('./src/components/icons/UpArrowIcon.vue')['default']
    UsersIcon: typeof import('./src/components/icons/UsersIcon.vue')['default']
  }
}
